// TOAST
export const TOAST_CREATE = "TOAST_CREATE";
export const TOAST_REMOVE = "TOAST_REMOVE";
export const TOAST_HIDE = "TOAST_HIDE";


// MESSAGE
export const MESSAGE_INCOMMING = "MESSAGE_INCOMMING";
export const MESSAGE_OUTGOING = "MESSAGE_OUTGOING";

// AUTH
export const AUTH_SIGNUP_REQUEST = "AUTH_SIGNUP_REQUEST";
export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS";
export const AUTH_SIGNUP_ERROR = "AUTH_SIGNUP_ERROR";

export const AUTH_LOGOUT = "AUTH_LOGOUT";


// CHAT
export const CHAT_CONNECT = "CHAT_CONNECT";
export const CHAT_CONNECTED = "CHAT_CONNECTED";

export const CHAT_DISCONNECT = "CHAT_DISCONNECT";
export const CHAT_DISCONNECTED = "CHAT_DISCONNECTED";

export const CHAT_FAILED = "CHAT_FAILED";


// USER
export const USER_GET_REQUEST = "USER_GET_REQUEST";
export const USER_GET_SUCCESS = "USER_GET_SUCCESS";
export const USER_GET_ERROR = "USER_GET_ERROR";

export const USER_EDIT_REQUEST = "USER_EDIT_REQUEST";
export const USER_EDIT_SUCCESS = "USER_EDIT_SUCCESS";
export const USER_EDIT_ERROR = "USER_EDIT_ERROR";
